import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./convexClientProvider";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-full flex flex-col w-full h-screen items-center justify-center">
        <main className="w-full flex justify-center">
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </main>
        <Toaster closeButton theme="dark" />
      </body>
    </html>
  );
}
